version: '3'

services:
  top-places-db-host:
    image: mariadb:10.1.35
    container_name: top-places-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - "3310:3306/tcp"

  top-places-app:
    container_name: top-places-app
    build:
      context: docker/php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
    - .:/var/www/top-places
    environment:
    - APP_DEBUG=1
    - PHP_IDE_CONFIG=docker.for.mac.localhost
    env_file:
    - .env

  top-places-webserver:
    build: docker/nginx
    container_name: top-places-webserver
    environment:
    - COMPOSE_HTTP_TIMEOUT=120
    ports:
    - "81:80/tcp"
    volumes:
    - ./var/log/nginx/:/var/log/nginx
    - .:/var/www/top-places
    expose:
    - 80
